// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serializeDemo/example/person.proto

package example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_person_715e64fd708de4e6, []int{0}
}
func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (dst *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(dst, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AllPerson struct {
	Per                  []*Person `protobuf:"bytes,1,rep,name=Per,proto3" json:"Per,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AllPerson) Reset()         { *m = AllPerson{} }
func (m *AllPerson) String() string { return proto.CompactTextString(m) }
func (*AllPerson) ProtoMessage()    {}
func (*AllPerson) Descriptor() ([]byte, []int) {
	return fileDescriptor_person_715e64fd708de4e6, []int{1}
}
func (m *AllPerson) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllPerson.Unmarshal(m, b)
}
func (m *AllPerson) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllPerson.Marshal(b, m, deterministic)
}
func (dst *AllPerson) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllPerson.Merge(dst, src)
}
func (m *AllPerson) XXX_Size() int {
	return xxx_messageInfo_AllPerson.Size(m)
}
func (m *AllPerson) XXX_DiscardUnknown() {
	xxx_messageInfo_AllPerson.DiscardUnknown(m)
}

var xxx_messageInfo_AllPerson proto.InternalMessageInfo

func (m *AllPerson) GetPer() []*Person {
	if m != nil {
		return m.Per
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "example.person")
	proto.RegisterType((*AllPerson)(nil), "example.all_person")
}

func init() {
	proto.RegisterFile("serializeDemo/example/person.proto", fileDescriptor_person_715e64fd708de4e6)
}

var fileDescriptor_person_715e64fd708de4e6 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2a, 0x4e, 0x2d, 0xca,
	0x4c, 0xcc, 0xc9, 0xac, 0x4a, 0x75, 0x49, 0xcd, 0xcd, 0xd7, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8,
	0x49, 0xd5, 0x2f, 0x48, 0x2d, 0x2a, 0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x87, 0x8a, 0x2a, 0xe9, 0x70, 0xb1, 0x41, 0x24, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18,
	0x15, 0x18, 0x35, 0x58, 0x83, 0x98, 0x32, 0x53, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53,
	0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x7d, 0x2e, 0xae, 0xc4, 0x9c, 0x9c,
	0x78, 0xa8, 0x0e, 0x45, 0x2e, 0xe6, 0x80, 0xd4, 0x22, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23,
	0x7e, 0x3d, 0xa8, 0x91, 0x7a, 0x10, 0xd9, 0x20, 0x90, 0x5c, 0x12, 0x1b, 0xd8, 0x3a, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x14, 0xea, 0x3e, 0x94, 0x00, 0x00, 0x00,
}
